config/routes.rb
Rails.application.routes.draw do
  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]

  resources :users, controller: "clearance/users", only: [:create] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]

  resources :users, controller: "clearance/users", only: [:create] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end

  resources :articles

  root 'welcome#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  validates :title, presence: true,
                    length: { minimum: 5 }
end

app/models/user.rb
class User < ApplicationRecord
  include Clearance::User
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Clearance::Controller
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	before_action :require_login, only: [:new, :edit]
	def index
		@articles = Article.all
	end

	def show
		@article = Article.find(params[:id])
	end

	def new
		@article = Article.new
	end

	def edit
		@article = Article.find(params[:id])
	end

	def create
		@article = Article.new(article_params)
		
		if @article.save
			redirect_to @article
		else
			render 'new'
		end
	end

	def update
		@article = Article.find(params[:id])

		if @article.update(article_params)
			redirect_to @article
		else
			render 'edit'
		end
	end

	def destroy
		@article = Article.find(params[:id])
		@article.destroy

		redirect_to articles_path
	end

	private
		def article_params
			params.require(:article).permit(:title, :text)
		end
end

app/controllers/blog_controller.rb
class BlogController < ApplicationController

	def index
	end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def markdown(text)
    options = {
      filter_html:     true,
      hard_wrap:       true,
      link_attributes: { rel: 'nofollow', target: "_blank" },
      space_after_headers: true,
      fenced_code_blocks: true
    }

    extensions = {
      autolink:           true,
      superscript:        true,
      disable_indented_code_blocks: true
    }

    renderer = Redcarpet::Render::HTML.new(options)
    markdown = Redcarpet::Markdown.new(renderer, extensions)

    markdown.render(text).html_safe
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/blog_helper.rb
module BlogHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_form.html.slim
= form_with(model: @article) do |form|
  .form-group
    - if @article.errors.any?
      #error_explanation
        h2
          = pluralize(@article.errors.count, "error")
          |  prohibited this article from being saved.
        ul
          - @article.errors.full_messages.each do |msg|
            li = msg
          end
    p 
      = form.label :title
      br
      = form.text_field :title, :class => 'form-text'

    p 
      = form.label :text
      br
      = form.text_area :text, :class => 'form-text'

    p
      = form.submit :class => 'btn btn-success'

app/views/articles/edit.html.slim
.container 
  .row
    .col-sm-12
      h1 Edit Article
      = render 'form'
      = link_to 'All Articles', articles_path

app/views/articles/index.html.slim
.container 
  .row
    .col-sm-12
      h1 All The Articles
      - unless signed_out?
        = link_to 'New Article', new_article_path, class: "btn btn-outline-primary"

      - @articles.each do |article|
        h3 = article.title
        = markdown(article.text)
        = link_to 'Show', article_path(article)
        - if signed_in?
          span &nbsp;|&nbsp;
          = link_to 'Edit', edit_article_path(article)
          span &nbsp;|&nbsp;
          = link_to 'Delete', article_path(article),
            method: :delete,
            data: { confirm: 'Are you sure?' }

app/views/articles/new.html.slim
.container 
  .row
    .col-sm-12
      h1 New Articles
      = render 'form'
      = link_to 'All Articles', articles_path

app/views/articles/show.html.slim
.container 
  .row
    .col-sm-12
      h3 = markdown(@article.title)

      p = markdown(@article.text)

      = link_to 'Edit', edit_article_path(@article)
      span &nbsp;|&nbsp;
      = link_to 'All Articles', articles_path

app/views/blog/index.html.slim
| hello world form template

app/views/layouts/application.html.slim
doctype html
html
  head
    meta content=("text/html; charset=UTF-8") http-equiv="Content-Type" /
    title DonovanHouse
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body
    - flash.each do |key, value|
      .container
        .row
          .col-12
            .alert.alert-warning *{:class => [key]}
              = value
    = yield
    .footer.text-muted
      .container
        .row
          .col-12
            - if signed_in?
              h5
                | Signed in as:&nbsp;
                = current_user.email
              = button_to 'Sign out', sign_out_path, method: :delete, :class => 'btn btn-secondary'
            - else
              = link_to 'Sign in', sign_in_path

            = link_to 'Donovanhouse', root_path

app/views/users/_form.html.slim
.text-field
  = form.label :email
  = form.text_field :email, type: 'email'
.password-field
  = form.label :password
  = form.password_field :password

app/views/users/new.html.slim
.container
  .row
    .col-sm-12
      #clearance.sign-up
        h2= t(".title")
        = form_for @user do |form|
          = render partial: '/users/form', object: form
          .submit-field
            = form.submit
          .other-links
            = link_to t(".sign_in"), sign_in_path

app/views/welcome/index.html.slim
.container 
  .row
    .col-sm-12
      h1 DonovanHouse
      = link_to 'My Blog', controller: 'articles'